- platform: iss
  show_on_map: False

- platform: aurora

- platform: workday
  country: US
  state: IL

- platform: ping
  host: !secret router_ip
  name: Router

- platform: ping
  host: !secret dns_ip
  name: DNS

- platform: ping
  host: www.google.com
  name: Google