- platform: generic
  name: chicago
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.zone.home.attributes.latitude }},{{ states.zone.home.attributes.longitude }}&zoom=14&size=500x500&maptype=roadmap
  limit_refetch_to_url_change: true

- platform: generic
  name: nasa
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}&zoom=5&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.binary_sensor.iss.attributes.lat }},{{ states.binary_sensor.iss.attributes.long }}
  limit_refetch_to_url_change: true

# - platform: usps
#   scan_interval: 10

- platform: generic
  name: radar
  hidden: true
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=LOT&brand=wui&num=10&delay=25&type=N0R&frame=0&scale=1.000&noclutter=0&showstorms=0&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=0&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24998536&lat=0&lon=0&label=you
