homeassistant:
  name: Synapse
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: !secret unit_system
  time_zone: !secret time_zone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages

automation: !include automation.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
group: !include_dir_merge_named groups
history: !include history.yaml
history_graph: !include history_graph.yaml
input_select: !include input_select.yaml
light: !include light.yaml
logbook: !include logbook.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors
switch: !include switch.yaml
script: !include scripts.yaml
zone: !include zones.yaml

discovery:
frontend:
updater:
config:
map:
sun:
shopping_list:

logger:
  default: info
  logs:
    homeassistant.components.http: warn
    pycec: warn

http:
  ssl_certificate: !secret fullchain_path
  ssl_key: !secret privkey_path
  trusted_networks: 192.168.1.0/24
  ip_ban_enabled: True
  login_attempts_threshold: 5
  api_password: !secret http_password

# usps:
#   name: USPS
#   username: !secret myusps_username
#   password: !secret myusps_password
