homeassistant:
  name: Synapse
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: !secret unit_system
  time_zone: !secret time_zone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

automation: !include_dir_merge_list automations
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
history: !include history.yaml
http: !include http.yaml
input_select: !include input_select.yaml
light: !include light.yaml
logbook: !include logbook.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
recorder: !include recorder.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml
script: !include scripts.yaml
zone: !include zones.yaml
weather: !include weather.yaml
group: !include_dir_merge_named groups

ios:
discovery:
frontend:
  javascript_version: latest
updater:
  include_used_components: true
config:
sun:

ecobee:
  api_key: !secret ecobee_api_key

apple_tv:
  - host: !secret apple_tv_ip
    login_id: !secret apple_tv_login_id
    name: Apple TV
    credentials: !secret apple_tv_credentials

vacuum:
  platform: xiaomi_miio
  name: Vacuum
  host: !secret vacuum_ip
  token: !secret vacuum_api_key

logger:
  default: info
  logs:
    homeassistant.components.http: warn
    pycec: warn

hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true

google:
  client_id: !secret gcal_client_id
  client_secret: !secret gcal_client_secret

# usps:
#   name: USPS
#   username: !secret myusps_username
#   password: !secret myusps_password
#   driver: 'chrome'
