- platform: unifi
  username: !secret icloud_username
  password: !secret myusps_password
  verify_ssl: false

# - platform: bluetooth_tracker

# - platform: icloud
#   username: !secret icloud_username
#   password: !secret icloud_password
#   name: !secret his_name
#   track_new_devices: no
