- platform: ups
  name: 'UPS'
  username: !secret upsmychoice_username
  password: !secret upsmychoice_password
  scan_interval: 3600

- platform: fedex
  name: 'Fedex'
  username: !secret fedexdeliverymanager_username
  password: !secret fedexdeliverymanager_password
  scan_interval: 3600

- platform: template
  sensors:
    packages_in_transit:
      friendly_name: "Packages in Transit"
      value_template: >
        {% macro in_transit(sensor) %}
          {{sensor.state|int - delivered(sensor)|int}}
        {% endmacro %}
        {% macro delivered(sensor) %}
          {% if 'delivered' in sensor.attributes %}
            {{sensor.attributes.delivered}}
          {% else %}
            None
          {% endif %}
        {% endmacro %}
        {{in_transit(states.sensor.usps_packages)|int + in_transit(states.sensor.ups)|int + in_transit(states.sensor.fedex)|int}}
    deliveries_today:
      friendly_name: "Today's Deliveries"
      value_template: >
        {% macro delivered(sensor) %}
          {% if 'delivered' in sensor.attributes %}
            {{sensor.attributes.delivered}}
          {% else %}
             None
          {% endif %}
        {% endmacro %}
        {{delivered(states.sensor.usps_packages)|int + delivered(states.sensor.ups)|int + delivered(states.sensor.fedex)|int}}