- platform: rest
  name: 'Entry Temperature'
  resource: !secret entry_temp_rest_link
  value_template: '{{ ((float(value_json.state.temperature) * 9 / 500 ) + 32) | round(1) }}'
  unit_of_measurement: '°F'
  scan_interval: 60

- platform: rest
  name: 'Entry Light'
  resource: !secret entry_light_rest_link
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: 'lx'
  scan_interval: 60

# - platform: rest
#   name: 'Entry Motion'
#   resource: !secret entry_light_rest_link
#   value_template: '{{ value_json.state.status }}'
#   scan_interval: 15

- platform: rest
  name: 'Laundry Temperature'
  resource: !secret laundry_temp_rest_link
  value_template: '{{ ((float(value_json.state.temperature) * 9 / 500 ) + 32) | round(1) }}'
  unit_of_measurement: '°F'
  scan_interval: 60

- platform: rest
  name: 'Laundry Light'
  resource: !secret laundry_light_rest_link
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: 'lx'
  scan_interval: 60

# - platform: rest
#   name: 'Laundry Motion'
#   resource: !secret laundry_light_rest_link
#   value_template: '{{ value_json.state.status }}'
#   scan_interval: 15