- platform: template
  sensors:
    his_status:
      value_template: '{{ states.input_select.his_status_dropdown.state }}'
      friendly_name: !secret his_name
    her_status:
      value_template: '{{ states.input_select.her_status_dropdown.state }}'
      friendly_name: !secret her_name


- platform: template
  sensors:
    router:
      value_template: '{% if is_state("binary_sensor.router", "on") %} {{ states.binary_sensor.router.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'
      unit_of_measurement: 'ms'
    dns:
      value_template: '{% if is_state("binary_sensor.dns", "on") %} {{ states.binary_sensor.dns.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'
      unit_of_measurement: 'ms'
    google:
      value_template: '{% if is_state("binary_sensor.google", "on") %} {{ states.binary_sensor.google.attributes.round_trip_time_avg }} {% else %}Offline{% endif %}'
      unit_of_measurement: 'ms'