- platform: synologydsm
  host: !secret synology_ip
  username: !secret http_username
  password: !secret http_password
  monitored_conditions:
    - volume_percentage_used

- platform: transmission
  name: Transmission
  host: !secret synology_ip
  username: !secret http_username
  password: !secret http_password
  monitored_variables:
    - current_status
    - download_speed
    - upload_speed
