- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature_min
    - temperature
    - temperature_max
    - nearest_storm_distance
    - cloud_cover
    - humidity
    - visibility
    - wind_speed
    - wind_bearing
  scan_interval: 120

- platform: wunderground
  api_key: 58c1b1db57e371d5
  monitored_conditions:
    - alerts

- platform: moon

- platform: template
  sensors:
    solar_angle:
      friendly_name: Sun Position
      unit_of_measurement: '°'
      value_template: "{{ '%+.1f'|format(states.sun.sun.attributes.elevation) }}"

- platform: template
  sensors:
    wind_dir:
      friendly_name: 'Wind Direction'
      icon_template: mdi:compass
      value_template: >-
        {% set wind_dir = states.sensor.dark_sky_wind_bearing.state %}
        {% if (wind_dir|float) <=22 %}North
        {% elif 22 < (wind_dir|float) <=67 %}North East
        {% elif 67 < (wind_dir|float) <=112 %}East
        {% elif 112 < (wind_dir|float) <=157 %}South East
        {% elif 157 < (wind_dir|float) <=202 %}South
        {% elif 202 < (wind_dir|float) <=247 %}South West
        {% elif 247 < (wind_dir|float) <=292 %}West
        {% elif 292 < (wind_dir|float) <=337 %}North West
        {% elif (wind_dir|float) > 337 %}North
        {%- endif %}